# Site settings

title: Partially Applicable
email: sabauma@gmail.com
description: My Ramblings
baseurl: ""
url: "http://sabauma.github.io"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
  hard_wrap: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

highlighter: pygments
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]

links:
    - github: "https://github.com/sabauma"

paginate: 10

